apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-nginx-deployment
  labels:
    app: nextjs-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-docker
  template:
    metadata:
      labels:
        app: nextjs-docker
    spec:
      containers:
      - name: nextjs-docker
        image: proposera.azurecr.io/proposera:v1
        ports:
        - containerPort: 3000
